- name: Status Badges
  uses: lucasvanmol/status-badges@v1.2.0
  with:
    path: README.md
    token: ${{ secrets.GITHUB_TOKEN }}
    active-emoji: ":green_circle:"
    stale-emoji: ":yellow_circle:"
    inactive-emoji: ":red_circle:"
